batch-size = 16
data-path = temp_data_class_11.csv
output-dir = chemprop_training/hyperparam_run_11
message-hidden-dim = 512
depth = 3
dropout = 0.0
ffn-hidden-dim = 512
ffn-num-layers = 1
splits-column = split_type
task-type = classification
init-lr = 0.0001
epochs = 500
num-workers = 0
accelerator = auto
devices = auto
rxn-mode = REAC_DIFF
multi-hot-atom-featurizer-mode = V2
frzn-ffn-layers = 0
ensemble-size = 1
activation = RELU
aggregation = norm
aggregation-norm = 100
multiclass-num-classes = 3
v-kl = 0.0
eps = 1e-08
alpha = 0.1
tracking-metric = val_loss
warmup-epochs = 2
max-lr = 0.001
final-lr = 0.0001
split = RANDOM
split-sizes = [0.8, 0.1, 0.1]
split-key-molecule = 0
num-replicates = 1
data-seed = 0
